gateways:
    local:
        connection:
            type: duckdb
            database: db.db
    remote:
        connection:
            type: bigquery
            method: service-account
            project: mahabot-390000
            keyfile: 'resources/corner-beers-390000-9bf2212e50c1.json'

default_gateway: local

model_defaults:
    dialect: bigquery
