gateways:
    local:
        connection:
            type: duckdb
            database: db.db
    remote:
        connection:
            type: bigquery
            project: my-project
            dataset: my-dataset
            location: US
            credentials: /path/to/credentials.json

default_gateway: local

model_defaults:
    dialect: bigquery
